project:
  type: website

website:
  title: "karlim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: dashboard.qmd
        text: Dashboard
  sidebar: 
    style: "docked"
    search: true
    contents: 
      - section: "R desde cero"
        contents: 
          - semana9.qmd
          - semana10.qmd
  

format:
  html:
    comments:
      giscus: 
        repo: quarto-dev/quarto-docs
    theme:
      light: cosmo
    toc: true
    




